blank_issues_enabled: false
contact_links:
  - name: Security Issue
    url: https://github.com/RMNCLDYO/claude-code-status-line/security/policy
    about: Please report security vulnerabilities here
  - name: Community Discussion
    url: https://github.com/RMNCLDYO/claude-code-status-line/discussions
    about: Ask questions and discuss ideas with the community